(() => {
 const E=QuizEngine, bank=QUESTIONS, key='studylab-csp-unit3-v1', main=document.querySelector('main');
 const names={quick:'Quick Quiz',full:'Full Unit Review',topic:'Practice by Topic',endless:'Endless Practice',missed:'Practice Missed Questions',weak:'Practice Weak Topics',retry:'Retry Quiz'};
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const topicName=id=>TOPICS.find(t=>t.id===id)?.name||id;
 let state; let storageOK=true; let toastTimer;
 try{state=E.load(localStorage.getItem(key),bank);}catch{state=E.empty();storageOK=false;}
 function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageOK=false;}notice();}
 function notice(){const n=document.getElementById('storage-note');n.hidden=storageOK;n.textContent='This browser cannot save progress. Your quiz works, but progress may be lost when you leave.';}
 const button=(text,action,cls='primary',disabled=false)=>`<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
 function toast(text){const t=document.getElementById('toast');t.textContent=text;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,4000);}
 function navigate(route){if(location.hash==='#'+route)render();else location.hash=route;}
 function home(){
 const best=state.bestScore;
 return `${state.session?`<div class="resume"><div><strong>Your quiz is waiting.</strong><p>${escape(names[state.session.mode])} · ${state.session.answers.length} answered</p></div>${button('Resume quiz →','resume')}</div>`:''}
 <section class="hero"><div><span class="unit-pill">UNIT 3 · STUDY LAB</span><h1>AP CSP<span>.</span></h1><h2>Intro to App Design</h2><p class="subtitle">Think you actually know Unit 3?</p><p class="description">Put your App Lab skills to the test. A little practice, a few lightbulb moments, and a lot more confidence.</p><div class="hero-tags"><span>${bank.length} original questions</span><span>No login needed</span><span>Your pace</span></div></div>
 <div class="illustration" aria-hidden="true"><span class="spark">✧</span><div class="editor"><div class="editor-top"><i></i><i></i><i></i><span>my-next-app.js</span></div><pre><span class="ln">1</span><span class="comment">// Small steps. Big ideas.</span>
<span class="ln">2</span><span class="token">onEvent</span>(<span class="str">"startButton"</span>, <span class="str">"click"</span>,
<span class="ln">3</span>  <span class="token">function</span>() {
<span class="ln">4</span>    <span class="token">setScreen</span>(<span class="str">"youGotThis"</span>);
<span class="ln">5</span>  });</pre></div><div class="output-chip">✓ &nbsp; Confidence unlocked.</div></div></section>
 <section class="progress-strip" aria-label="Your progress"><div class="intro"><span class="mini-icon" aria-hidden="true">↗</span><div><span>Your progress</span><small>A little better with every question.</small></div></div><div class="metric"><strong>${state.totalAnswered}</strong><small>Questions answered</small></div><div class="metric"><strong>${state.totalAnswered?E.percent(state.totalCorrect,state.totalAnswered)+'%':'—'}</strong><small>Overall accuracy</small></div><div class="metric"><strong>${best?best.percentage+'%':'—'}</strong><small>Best completed quiz</small></div></section>
 <section><div class="section-head"><h2>Choose your challenge</h2><p>Same unit. Four ways to make it stick.</p></div><div class="mode-grid">
 ${modeCard('quick','ϟ','Quick Quiz','A quick confidence check. Ten questions, fresh every time.','10 questions · All topics','QUICK START')}
 ${modeCard('full','▤','Full Unit Review','The big picture. Balanced practice across every Unit 3 topic.','25 questions · Balanced coverage')}
 ${modeCard('topics','⌘','Practice by Topic','Find your focus. Work on the concepts you want to master.','8 topic groups · Targeted practice')}
 ${modeCard('endless','∞','Endless Practice','Stay in the flow. Keep practicing for as long as you like.','Untimed · Stop whenever you want')}
 </div></section><div class="tip"><span class="bulb" aria-hidden="true">✧</span><p><strong>Understanding beats memorizing.</strong> Every answer comes with a short explanation. Take a moment to connect the why.</p></div>`;
 }
 function modeCard(action,icon,title,description,detail,badge){return `<button class="mode-card ${badge?'featured':''}" data-action="${action}"><div class="mode-top"><span class="mode-icon" aria-hidden="true">${icon}</span>${badge?`<span class="badge">${badge}</span>`:''}</div><h3>${title}</h3><p>${description}</p><div class="card-bottom"><span>${detail}</span><span class="arrow" aria-hidden="true">↗</span></div></button>`;}
 function topics(){return `<div class="page-heading"><span class="eyebrow">One concept at a time</span><h1>Find your focus.</h1><p>Pick a topic. Practice every question in that group, including real-world scenarios.</p></div><div class="topic-grid">${TOPICS.map(t=>{const p=state.topics[t.id];return `<button class="topic-card" data-action="topic" data-topic="${t.id}"><h3>${t.name}</h3><p>${t.description}</p><small>${bank.filter(q=>q.topic===t.id).length} questions · ${p?.answered?E.percent(p.correct,p.answered)+'% accuracy':'Not practiced yet'} &nbsp; →</small></button>`;}).join('')}</div>`;}
 function quiz(){
 const s=state.session;if(!s)return home();const q=bank.find(q=>q.id===s.ids[s.index]);const score=s.answers.filter(a=>a.correct).length;
 const answer=s.answers[s.index];
 return `<div class="quiz-wrap"><div class="quiz-top"><span class="mode-name">${escape(names[s.mode]||'Practice')}${s.topic?' · '+escape(topicName(s.topic)):''}</span>${button('Finish session','finish','text-button')}</div><div class="quiz-info"><span>Question ${s.index+1} ${s.mode==='endless'?'· Round '+s.round:'of '+s.ids.length}</span><span>Score <strong>${score} / ${s.answers.length}</strong></span></div><div class="bar" role="progressbar" aria-label="Answered questions in this round" aria-valuemin="0" aria-valuemax="${s.ids.length}" aria-valuenow="${s.answers.length}"><span style="width:${s.answers.length/s.ids.length*100}%"></span></div>
 <section class="question-card"><div class="question-tags"><span>${escape(topicName(q.topic))}</span><span class="difficulty ${q.difficulty}">${q.difficulty}</span>${q.kind==='scenario'?'<span class="badge">Real-world scenario</span>':''}</div><h1>${escape(q.question)}</h1>${q.code?`<div class="code-block"><div class="code-title">APP LAB · JAVASCRIPT</div><pre><code>${escape(q.code)}</code></pre></div>`:''}<div class="choices" role="group" aria-label="Choose one answer">${s.orders[s.index].map((original,i)=>{let cls=s.selected===i?' selected':'';if(s.locked){if(original===q.correctAnswer)cls=' correct';else if(s.selected===i)cls=' wrong';}return `<button class="choice${cls}" data-action="choose" data-index="${i}" aria-pressed="${s.selected===i}" ${s.locked?'disabled':''}><span class="letter" aria-hidden="true">${s.locked&&original===q.correctAnswer?'✓':s.locked&&s.selected===i?'×':String.fromCharCode(65+i)}</span><span>${escape(q.choices[original])}</span>${s.locked&&(original===q.correctAnswer||s.selected===i)?`<span class="answer-label">${original===q.correctAnswer?'CORRECT':'YOUR ANSWER'}</span>`:''}</button>`;}).join('')}</div>
 ${s.locked?`<div class="feedback ${answer.correct?'':'incorrect'}" role="status"><h2>${answer.correct?'That’s right.':'A good one to learn from.'}</h2>${!answer.correct?`<p class="right-answer">Correct answer: ${escape(q.choices[q.correctAnswer])}</p>`:''}<p>${escape(q.explanation)}</p></div>`:''}
 <div class="quiz-bottom"><span class="keyboard-hint">Choose with <kbd>1</kbd>–<kbd>4</kbd> · <kbd>Enter</kbd> to ${s.locked?'continue':'check'}</span>${s.locked?button(s.index===s.ids.length-1?(s.mode==='endless'?'Next round →':'See results →'):'Next Question →','next'):button('Check answer','submit','primary',s.selected===null)}</div></section>${s.mode==='endless'?`<p class="round-note">No repeats within a round. Each round covers all ${bank.length} questions; a fresh round reshuffles the bank. Finish anytime to see your results.</p>`:''}</div>`;
 }
 function accuracyRows(values,all=false){return TOPICS.filter(t=>all||values[t.id]?.answered).map(t=>{const v=values[t.id]||{answered:0,correct:0};const pc=E.percent(v.correct,v.answered);return `<div class="accuracy-row ${pc<80?'weak':''}"><span>${t.name}</span><div class="bar"><span style="width:${pc}%"></span></div><span class="value">${v.answered?pc+'%':'—'}<br><small>${v.correct}/${v.answered}</small></span></div>`;}).join('');}
 function results(){const r=state.lastResult;if(!r)return home();return `<div class="quiz-wrap"><section class="results-hero"><span class="unit-pill">SESSION COMPLETE</span><h1>${r.percentage>=80?'Look at you go.':r.answered?'Every question is progress.':'Ready when you are.'}</h1><p>${r.complete?'Review complete.':r.answered+' questions practiced.'} ${r.answered?'Here’s what clicked, and where to focus next.':'Start a quiz to build your confidence.'}</p><div class="score-ring" style="--angle:${r.percentage*3.6}deg"><div><strong>${r.percentage}%</strong><small>accuracy</small></div></div><div class="result-counts"><span><strong class="good">${r.correct}</strong> correct</span><span><strong class="bad">${r.answered-r.correct}</strong> incorrect</span><span><strong>${r.answered}</strong> answered</span></div></section><div class="actions results-actions">${button('Retry Quiz','retry')}${button('Practice Missed Questions','missed','secondary',!r.missed.length)}${button('Practice Weak Topics','weak','secondary',!r.weak.length)}${button('Return Home','home','secondary')}</div><section class="panel"><h2>Your accuracy by topic</h2>${r.answered?accuracyRows(r.topics):'<p class="empty-note">No questions answered in this session.</p>'}<p class="weak-note">${r.weak.length?'Focus next: '+escape(r.weak.map(topicName).join(' · '))+'.':'Keep the momentum going with another round.'} Topics below 80% are suggested for practice.</p></section></div>`;}
 function stats(){return `<div class="page-heading"><span class="eyebrow">Your learning, at a glance</span><h1>Small steps add up.</h1><p>Your practice history stays on this browser. Every submitted answer counts.</p></div><div class="stats-grid"><div class="stat-card"><strong>${state.totalAnswered}</strong><span>Questions answered</span></div><div class="stat-card"><strong>${state.totalCorrect}</strong><span>Correct answers</span></div><div class="stat-card"><strong>${state.totalAnswered?E.percent(state.totalCorrect,state.totalAnswered)+'%':'—'}</strong><span>Overall accuracy</span></div><div class="stat-card"><strong>${state.bestScore?state.bestScore.percentage+'%':'—'}</strong><span>Best completed quiz</span>${state.bestScore?`<small>${state.bestScore.correct}/${state.bestScore.answered} correct</small>`:''}</div></div><div class="stats-lower"><section class="panel"><h2>Topic breakdown</h2>${accuracyRows(state.topics,true)}<p class="weak-note">Accuracy includes all attempts. Below 80%? That’s a great place to practice.</p></section><section class="panel"><h2>Recent sessions</h2>${state.history.length?state.history.slice(0,6).map(h=>`<div class="history-row"><div>${escape(names[h.mode]||'Practice')}<small>${new Date(h.finishedAt).toLocaleDateString()} · ${h.correct}/${h.answered} correct</small></div><strong>${h.percentage}%</strong></div>`).join(''):'<p class="empty-note">Finish your first quiz to see it here.</p>'}<div class="actions">${button('Review recent misses ('+state.recentMissed.length+')','recent','secondary',!state.recentMissed.length)}</div><p class="weak-note">Up to 40 distinct recent misses. A correct retry removes a question from this list.</p></section></div><div class="stats-foot"><span>No account. No leaderboard. Just your progress.</span>${button('Reset Progress','reset','secondary')}</div>`;}
 function about(){return `<article class="about"><div class="page-heading"><span class="eyebrow">A little context</span><h1>Built for Unit 3.</h1></div><p>This independent study resource covers Code.org AP Computer Science Principles Unit 3: Intro to App Design. All ${bank.length} questions are original, including 32 added real-world scenarios. It is not an official Code.org assessment.</p><p>Scope: purpose, input and output, interface design, user-centered design, sequential and event-driven execution, App Lab commands, strings, comments, debugging, testing, and iterative development. No questions require loops, conditionals, arrays, data-processing patterns, or custom procedures.</p><p>For code questions, assume referenced elements and uploaded media exist unless the question explicitly describes an error. Example programs are text to reason about; they are not executed by this website.</p><h2>Curriculum references</h2><ul><li><a href="https://studio.code.org/courses/csp-2025/units/3/lessons/5" target="_blank" rel="noopener">Unit 3: Intro to Programming</a></li><li><a href="https://studio.code.org/courses/csp-2022/units/3/lessons/7" target="_blank" rel="noopener">Unit 3: Debugging (2022 edition)</a></li><li><a href="https://studio.code.org/docs/ide/applab/expressions/randomNumber_min_max" target="_blank" rel="noopener">App Lab randomNumber documentation</a></li><li><a href="https://lesson-plans.code.org/applab-intro/20220317223454/teacher-lesson-plans/Intro-to-App-Lab.pdf" target="_blank" rel="noopener">Intro to App Lab teacher guide</a></li></ul><p>Lesson numbering can vary by curriculum year. This bank follows the Intro to App Design scope specified for this study site.</p><h2>How practice works</h2><p>Questions and answer order are shuffled. Full Unit Review draws 3–4 questions from each of the eight topic groups. Topic practice includes the full group. Endless Practice uses all questions without repetition in each round, then begins another shuffled round.</p><p>Progress is stored in localStorage on this browser and website address. It does not sync across devices. “Best completed quiz” is the highest percentage on a fully completed quiz, breaking ties by question count. Missed practice uses this session’s mistakes; weak-topic practice draws from topics with less than 80% accuracy in this session.</p>${button('Back to practice','home','secondary')}</article>`;}
 function render(){const route=location.hash.slice(1)||'home';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',route===a.dataset.nav));main.innerHTML=`<div class="screen-enter">${route==='stats'?stats():route==='topics'?topics():route==='quiz'&&state.session?quiz():route==='results'&&state.lastResult?results():route==='about'?about():home()}</div>`;notice();}
 function start(mode,ids,topic){if(state.session)E.finish(state);const s=E.create(bank,mode,ids,topic);if(!s){toast('There are no questions to practice here yet.');return;}state.session=s;save();navigate('quiz');window.scrollTo(0,0);}
 function act(action,el){
 if(['quick','full','endless'].includes(action))return start(action);
 if(action==='topics')return navigate('topics');if(action==='topic')return start('topic',null,el.dataset.topic);
 if(action==='resume')return navigate('quiz');if(action==='home')return navigate('home');
 if(action==='choose'){const s=state.session;if(!s||s.locked)return;s.selected=Number(el.dataset.index);save();render();document.querySelector(`[data-index="${s.selected}"]`)?.focus();return;}
 if(action==='submit'){if(E.answer(state,bank)){save();render();document.querySelector('[data-action="next"]')?.focus();}return;}
 if(action==='next') {const s=state.session;if(!s?.locked)return;if(s.index===s.ids.length-1){if(s.mode==='endless'){const round=s.round+1;E.finish(state);state.session=E.create(bank,'endless');state.session.round=round;toast('Round '+round+' · A fresh shuffle. Finish whenever you like.');}else{E.finish(state);save();navigate('results');window.scrollTo(0,0);return;}}else{s.index++;s.selected=null;s.locked=false;}save();render();main.focus();window.scrollTo(0,0);return;}
 if(action==='finish'){if(state.session)E.finish(state);save();navigate('results');window.scrollTo(0,0);return;}
 if(action==='retry'){const r=state.lastResult;return start(r.mode==='endless'?'endless':'retry',r.ids,r.topic);}
 if(action==='missed')return start('missed',state.lastResult.missed);
 if(action==='weak')return start('weak',bank.filter(q=>state.lastResult.weak.includes(q.topic)).map(q=>q.id));
 if(action==='recent')return start('missed',state.recentMissed);
 if(action==='reset')document.getElementById('confirm').showModal();
 }
 main.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)act(el.dataset.action,el);});
 document.addEventListener('keydown',e=>{if(location.hash!=='#quiz'||!state.session||document.querySelector('dialog[open]')||e.altKey||e.ctrlKey||e.metaKey)return;const s=state.session;if(/^[1-4]$/.test(e.key)&&!s.locked){e.preventDefault();act('choose',{dataset:{index:Number(e.key)-1}});}else if(e.key==='Enter'&&(e.target===main||e.target.closest('[data-action="choose"]'))){e.preventDefault();act(s.locked?'next':'submit');}});
 document.getElementById('cancel-reset').onclick=()=>document.getElementById('confirm').close();
 document.getElementById('confirm-reset').onclick=()=>{state=E.empty();save();document.getElementById('confirm').close();render();toast('Progress reset. A fresh start.');};
 document.getElementById('share').onclick=async()=>{const url=location.href.split('#')[0];try{if(navigator.share){await navigator.share({title:'AP CSP Unit 3 Study Lab',text:'Think you know Unit 3? Practice App Lab with me.',url});}else{await navigator.clipboard.writeText(url);toast('Link copied. Send it to your study group.');}}catch(e){if(e.name!=='AbortError')toast('Share this page by copying its address from your browser.');}};
 addEventListener('hashchange',()=>{render();main.focus();window.scrollTo(0,0);});
 if(!location.hash&&state.session)location.hash='quiz';else render();
})();
